version: "3.8"

services:
  server:
    build: .
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on: 
      - mongo
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: panos
      MONGO_INITDB_ROOT_PASSWORD: panathinaikos
    ports:
      - 27017:27017
  